=== Daria-del/Lab_xml_1/src/main/resources/doc.dtd
<?xml version="1.0" encoding="UTF-8" ?>

        <!ELEMENT Services (Service*)>

        <!ELEMENT Service (Name, Cost)>

        <!ELEMENT Name EMPTY>
        <!ATTLIST Name
                name CDATA #REQUIRED
                >

        <!ELEMENT Cost EMPTY>
        <!ATTLIST Cost
                count CDATA #REQUIRED
                >

=== Daria-del/Lab_xml_1/src/main/resources/my_xml.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Services SYSTEM "doc.dtd">
<Services>
    <Service>
        <Name name="Strigka kaskad"/>
        <Cost count="1050"/>
    </Service>
    <Service>
        <Name name="Strigka kare"/>
        <Cost count="1250"/>
    </Service>
    <Service>
        <Name name="Strigka bob"/>
        <Cost count="1400"/>
    </Service>
    <Service>
        <Name name="Strigka modelnaya"/>
        <Cost count="1850"/>
    </Service>
    <Service>
        <Name name="Ukladka utugom korokie"/>
        <Cost count="590"/>
    </Service>
    <Service>
        <Name name="Ukladka utugom dlinnie"/>
        <Cost count="980"/>
    </Service>
</Services>
